package pl.edu.pjwst.s8132.ShoppingCart;


/**
* pl/edu/pjwst/s8132/ShoppingCart/_ShoppingCartImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ShoppingCart.idl
* niedziela, 14 czerwca 2015 04:27:31 CEST
*/

public abstract class _ShoppingCartImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements pl.edu.pjwst.s8132.ShoppingCart.ShoppingCart, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ShoppingCartImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_p", new java.lang.Integer (0));
    _methods.put ("addProduct", new java.lang.Integer (1));
    _methods.put ("removeProduct", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // pl/edu/pjwst/s8132/ShoppingCart/ShoppingCart/_get_p
       {
         int $result[] = null;
         $result = this.p ();
         out = $rh.createReply();
         pl.edu.pjwst.s8132.ShoppingCart.ShoppingCartPackage.productsHelper.write (out, $result);
         break;
       }

       case 1:  // pl/edu/pjwst/s8132/ShoppingCart/ShoppingCart/addProduct
       {
         int productId = in.read_long ();
         this.addProduct (productId);
         out = $rh.createReply();
         break;
       }

       case 2:  // pl/edu/pjwst/s8132/ShoppingCart/ShoppingCart/removeProduct
       {
         int productId = in.read_long ();
         this.removeProduct (productId);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:pl/edu/pjwst/s8132/ShoppingCart/ShoppingCart:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ShoppingCartImplBase
