package pl.edu.pjwst.s8132.ShoppingCart;


/**
* pl/edu/pjwst/s8132/ShoppingCart/ShoppingCartOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ShoppingCart.idl
* niedziela, 14 czerwca 2015 04:27:31 CEST
*/

public interface ShoppingCartOperations 
{
  int[] p ();
  void addProduct (int productId);
  void removeProduct (int productId);
} // interface ShoppingCartOperations
