package pl.edu.pjwstk.s8132.sri.corba.arytmetyka;


/**
* ArytmetykaPackage/DzieleniePrzezZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* niedziela, 31 maja 2015 12:29:06 CEST
*/

public final class DzieleniePrzezZero extends org.omg.CORBA.UserException
{

  public DzieleniePrzezZero ()
  {
    super(DzieleniePrzezZeroHelper.id());
  } // ctor


  public DzieleniePrzezZero (String $reason)
  {
    super(DzieleniePrzezZeroHelper.id() + "  " + $reason);
  } // ctor

} // class DzieleniePrzezZero
