package pl.edu.pjwst.s8132.ShoppingCart;


/**
* pl/edu/pjwst/s8132/ShoppingCart/CartItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ShoppingCart.idl
* niedziela, 14 czerwca 2015 12:13:08 CEST
*/

public final class CartItem implements org.omg.CORBA.portable.IDLEntity
{
  public int amount = (int)0;
  public pl.edu.pjwst.s8132.ShoppingCart.Product product = null;

  public CartItem ()
  {
  } // ctor

  public CartItem (int _amount, pl.edu.pjwst.s8132.ShoppingCart.Product _product)
  {
    amount = _amount;
    product = _product;
  } // ctor

} // class CartItem
