package pl.edu.pjwst.s8132.ShoppingCart;


/**
* pl/edu/pjwst/s8132/ShoppingCart/Product.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ShoppingCart.idl
* niedziela, 14 czerwca 2015 12:13:08 CEST
*/

public final class Product implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String name = null;

  public Product ()
  {
  } // ctor

  public Product (int _id, String _name)
  {
    id = _id;
    name = _name;
  } // ctor

} // class Product
