package pl.edu.pjwst.s8132.ShoppingCart;


/**
* pl/edu/pjwst/s8132/ShoppingCart/ProductsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ShoppingCart.idl
* niedziela, 14 czerwca 2015 12:13:08 CEST
*/

abstract public class ProductsHelper
{
  private static String  _id = "IDL:pl/edu/pjwst/s8132/ShoppingCart/Products:1.0";

  public static void insert (org.omg.CORBA.Any a, pl.edu.pjwst.s8132.ShoppingCart.Product[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static pl.edu.pjwst.s8132.ShoppingCart.Product[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = pl.edu.pjwst.s8132.ShoppingCart.ProductHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (pl.edu.pjwst.s8132.ShoppingCart.ProductsHelper.id (), "Products", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static pl.edu.pjwst.s8132.ShoppingCart.Product[] read (org.omg.CORBA.portable.InputStream istream)
  {
    pl.edu.pjwst.s8132.ShoppingCart.Product value[] = null;
    int _len0 = istream.read_long ();
    value = new pl.edu.pjwst.s8132.ShoppingCart.Product[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = pl.edu.pjwst.s8132.ShoppingCart.ProductHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, pl.edu.pjwst.s8132.ShoppingCart.Product[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      pl.edu.pjwst.s8132.ShoppingCart.ProductHelper.write (ostream, value[_i0]);
  }

}
