package pl.edu.pjwst.s8132.ShoppingCart;


/**
* pl/edu/pjwst/s8132/ShoppingCart/ShoppingCartOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ShoppingCart.idl
* niedziela, 14 czerwca 2015 12:13:08 CEST
*/

public interface ShoppingCartOperations 
{
  pl.edu.pjwst.s8132.ShoppingCart.CartItem[] cartItems ();
  void addProduct (pl.edu.pjwst.s8132.ShoppingCart.CartItem cartItem);
  void checkOut ();
} // interface ShoppingCartOperations
