package pl.edu.pjwst.s8132.ShoppingCart;


/**
* pl/edu/pjwst/s8132/ShoppingCart/ShopOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ShoppingCart.idl
* niedziela, 14 czerwca 2015 12:13:08 CEST
*/

public interface ShopOperations 
{
  pl.edu.pjwst.s8132.ShoppingCart.Product[] products ();
} // interface ShopOperations
