package pl.edu.pjwst.s8132.ShoppingCart;


/**
* pl/edu/pjwst/s8132/ShoppingCart/ShopHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ShoppingCart.idl
* niedziela, 14 czerwca 2015 12:13:08 CEST
*/

abstract public class ShopHelper
{
  private static String  _id = "IDL:pl/edu/pjwst/s8132/ShoppingCart/Shop:1.0";

  public static void insert (org.omg.CORBA.Any a, pl.edu.pjwst.s8132.ShoppingCart.Shop that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static pl.edu.pjwst.s8132.ShoppingCart.Shop extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (pl.edu.pjwst.s8132.ShoppingCart.ShopHelper.id (), "Shop");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static pl.edu.pjwst.s8132.ShoppingCart.Shop read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ShopStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, pl.edu.pjwst.s8132.ShoppingCart.Shop value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static pl.edu.pjwst.s8132.ShoppingCart.Shop narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof pl.edu.pjwst.s8132.ShoppingCart.Shop)
      return (pl.edu.pjwst.s8132.ShoppingCart.Shop)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      pl.edu.pjwst.s8132.ShoppingCart._ShopStub stub = new pl.edu.pjwst.s8132.ShoppingCart._ShopStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static pl.edu.pjwst.s8132.ShoppingCart.Shop unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof pl.edu.pjwst.s8132.ShoppingCart.Shop)
      return (pl.edu.pjwst.s8132.ShoppingCart.Shop)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      pl.edu.pjwst.s8132.ShoppingCart._ShopStub stub = new pl.edu.pjwst.s8132.ShoppingCart._ShopStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
