package pl.edu.pjwst.s8132.ShoppingCart.ShoppingCartPackage;


/**
* pl/edu/pjwst/s8132/ShoppingCart/ShoppingCartPackage/productsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ShoppingCart.idl
* niedziela, 14 czerwca 2015 04:27:31 CEST
*/

public final class productsHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public productsHolder ()
  {
  }

  public productsHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pl.edu.pjwst.s8132.ShoppingCart.ShoppingCartPackage.productsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pl.edu.pjwst.s8132.ShoppingCart.ShoppingCartPackage.productsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pl.edu.pjwst.s8132.ShoppingCart.ShoppingCartPackage.productsHelper.type ();
  }

}
